carteralbrecht/chatapp

- .gitignore
> testing PR

- .gitignore
> CU-fmvyn2_add-cool-feature

- .gitignore
Testing clickup with John's setup
> CU-fmw1ty_Some-new-task-by-John

- .gitignore
> CU-frtc5u_design-explore-page

- client/src/Register.jsx
- server/api/routes/users.js
> CU-fwuabk_attach-usernames-to-account

- mobile/client/src/screens/Registration.js
Designed mobile registration page
> CU-fyrkec_mobile-registration-page

- mobile/.gitignore
- mobile/App.js
- mobile/app.json
- mobile/client/src/components/AddMessage.js
- mobile/client/src/components/ChatLog.js
- mobile/client/src/screens/LoginScreen.js
- mobile/client/src/screens/MessageScreen.js
Basic mobile chat. Still needs some modifications.
> CU-frtgqt_basic-mobile-chat

- client/src/BottomBar.js
- client/src/Register.jsx
- client/src/SignInForm.jsx
- client/src/config.js
- server/api/lib/oktaClient.js
- server/api/routes/users.js
- server/package-lock.json
- server/package.json
Password recovery and misc changes.  Uses built-in okta recovery email.  API does not provide a way to send email ourselves and custom email template costs money.  I will probably go back and change this later to use a recovery question and answer because I don't like the default email template.
> Password recovery

- mobile/App.js
- mobile/client/src/screens/LoginScreen.js
- mobile/client/src/screens/MessageScreen.js
- mobile/client/src/screens/Registration.js
- mobile/package-lock.json
- mobile/package.json
- mobile/server/api/routes/AppNavigator.js
Navigation to register screen and chat screen.
> CU-g2u4tv_Add-navigation-feature

- client/src/components/dashboard/dashboard.jsx
- server/api/routes/rooms.js
- server/models/Room.js
Adds tags array to room schema, Adds search endpoint for searching by tags, also adds simple function for querying on front end
> CU-geq2pm_Room-search-and-tags

- mobile/client/src/components/AddMessage.js
- mobile/client/src/screens/MessageScreen.js
- mobile/package-lock.json
- mobile/package.json
- mobile/server/api/routes/AppNavigator.js
- mobile/server/api/routes/ChatDrawerContent.js
- mobile/server/api/routes/ChatDrawerNavigator.js
Chat room now has a side drawer that shows members in the group chat.
> CU-frtgud_Add-mobile-side-panel-Chatroom-list-panel

- mobile/src/AppNavigator.js
- mobile/src/screens/Dashboard.js
- mobile/src/screens/LoginScreen.js
- mobile/src/screens/SearchRooms.js
- mobile/src/screens/UpdateUser.js
I think there are a lot of commits because I had to merge my branch with master to get some of the navigation files. Only actual changes were the last two commits.
> CU-gjxvmk_Mobile-App-Screen-Navigation

- client/package.json
- client/src/components/dashboard/dashboard.jsx
- package.json
restore search modal changes i had done
> CU-gmu6tz_web-room-search-modal

- client/src/components/dashboard/dashboard.jsx
> Some buttons for carter

- client/src/components/dashboard/dashboard.jsx
> import AddIcon

- client/public/index.html
- client/src/components/dashboard/dashboard.jsx
- client/src/components/home/home.jsx
- client/src/components/navbar/navbar.jsx
- client/src/components/register/register.jsx
- client/src/components/signin/signin.jsx
- client/src/components/signin/signinForm.jsx
Theme should be constant throughout the pages now. Also Home page will not be visited any longer with new redirecting.
> Jacob frontend cleanup

- mobile/src/screens/Dashboard.js
- mobile/src/screens/SearchRooms.js
Delete confirmation alert works locally, don't have my server stuff set up yet but I tested it in a different place for syntax
> CU-grrmr9_Delete-confirmation

- client/src/components/chat/bottomBar.jsx
- client/src/components/chat/chat.css
- client/src/components/chat/chat.jsx
- client/src/components/dashboard/dashboard.jsx
Chat opens on join Room click, seperate rooms dash into their own card (Cards and chat component need work still)
> CU-gmuctm_open-chat-on-join-room

- client/package-lock.json
- client/package.json
- client/src/components/chat/chat.jsx
- client/src/components/dashboard/dashboard.jsx
- package-lock.json
- server/index.js
- server/package-lock.json
Did not fix web chat, but made important server adjustments and updated client. Probably best to merge this because people will need these changes to work on web chat.
> Cu gutdk1 try to fix web chat please work for the love of god

- client/src/components/dashboard/dashboard.jsx
Dash cards are better see discord web channel for Screenshots
> CU-guuutw_dash-cards
